In [1]:
import pandas as pd
import numpy as np
import os
import getpass
from datetime import datetime
from kaggle_loader import KaggleToSQLPipeline

d:\Project\Data Analytics\venv\football_db\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Connect to database

DB_USER = "root"
pwd = getpass.getpass(f"Enter password for {DB_USER}: ")

# Initialize the pipeline
pipe = KaggleToSQLPipeline(db_name="football", user=DB_USER, password=pwd, port="3307")

# Download the data

data_folder = pipe.download_data("kamrangayibov/football-data-european-top-5-leagues")

file_path = os.path.join(data_folder, r'kaggle_dataset/')

Validating database connection...
Connection successful!
--- Downloading kamrangayibov/football-data-european-top-5-leagues ---
Data saved to: d:\Project\Data Analytics\venv\football_db\Codes\football-analytics\Python\datasets\kamrangayibov\football-data-european-top-5-leagues\versions\1

In [3]:
# Create a list containing only files that end with '.csv'
csv_files = [f for f in os.listdir(file_path) if f.endswith('.csv')]

print(csv_files)

['coaches.csv', 'leagues.csv', 'matches.csv', 'players.csv', 'referees.csv', 'scores.csv', 'seasons.csv', 'stadiums.csv', 'standings.csv', 'teams.csv']

In [4]:
# Preview the dataset using pandas dataframe

csv_to_load = os.path.join(file_path, "coaches.csv")

coach_df = pd.read_csv(csv_to_load)
display(coach_df.head(10))

   coach_id                  name  team_id nationality
0        34                   NaN      354         NaN
1        35                   NaN      356         NaN
2        36                   NaN      389         NaN
3        37                   NaN      397         NaN
4        38                   NaN      402         NaN
5        39                   NaN      563         NaN
6        40                   NaN     1044         NaN
7       101          Kersten Kuhl        1     Germany
8       102  Pellegrino Matarazzo        2         USA
9       103           Xabi Alonso        3       Spain

In [5]:
# Preview the dataset using pandas dataframe

csv_to_load = os.path.join(file_path, "teams.csv")

team_df = pd.read_csv(csv_to_load)
display(team_df.head(10))

,team_id,name,founded_year,stadium_id,league_id,coach_id,cresturl
0,77,Athletic Club,1898.0,61,3,61,https://crests.football-data.org/77.png
1,78,Club Atlético de Madrid,1903.0,62,3,62,https://crests.football-data.org/78.svg
2,79,CA Osasuna,1920.0,63,3,63,https://crests.football-data.org/79.svg
3,81,FC Barcelona,1899.0,64,3,64,https://crests.football-data.org/81.svg
4,82,Getafe CF,1946.0,65,3,65,https://crests.football-data.org/82.png
5,83,Granada CF,1931.0,66,3,66,https://crests.football-data.org/83.svg
6,86,Real Madrid CF,1902.0,67,3,67,https://crests.football-data.org/86.png
7,87,Rayo Vallecano de Madrid,1924.0,68,3,68,https://crests.football-data.org/87.svg
8,89,RCD Mallorca,1916.0,69,3,69,https://crests.football-data.org/89.png
9,90,Real Betis Balompié,1907.0,70,3,70,https://crests.football-data.org/90.png

In [6]:
"""
source: https://en.wikipedia.org/wiki/List_of_Premier_League_managers
"""

'\nsource: https://en.wikipedia.org/wiki/List_of_Premier_League_managers\n'

In [ ]:
# --- Usage Example ---
from scrape_pl_manager import WikiTableParser

parser = WikiTableParser('https://en.wikipedia.org/wiki/List_of_Premier_League_managers')
pl_coach = parser.parse_managers_table()
if pl_coach is not None:
    print(pl_coach.head(3))

               Name      Nat.     Club              From             Until  \
1     George Graham  Scotland  Arsenal       14 May 1986  21 February 1995
2  Stewart Houston‡  Scotland  Arsenal  22 February 1995       8 June 1995
3       Bruce Rioch  Scotland  Arsenal       8 June 1995    12 August 1996

  Duration(days) Years inLeague Ref.
1           3205      1992–1995  [2]
2            106           1995  [3]
3            431      1995–1996  [2]

In [8]:
pl_coach['From'].fillna('')

1            14 May 1986
2       22 February 1995
3            8 June 1995
4         12 August 1996
5      13 September 1996
             ...
495     14 November 2022
496        9 August 2023
497     19 December 2024
498      2 November 2025
499     12 November 2025
Name: From, Length: 499, dtype: object

In [9]:
pl_coach[pl_coach['From'].astype(str).str.contains('\[.*\]', regex=True)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36]
67,Roberto De Zerbi,Italy,Brighton & Hove Albion,18 September 2022[b],19 May 2024,1195,2022–2024,
179,Scott Parker,England,Fulham,28 February 2019[c],28 June 2021,851,20192020–2021,
185,Iain Dowie,Northern Ireland,Hull City,17 March 2010[d],9 May 2010,53,2010,[92]
187,Mike Phelan,England,Hull City,22 July 2016[e],3 January 2017,165,2016–2017,
215,Craig Shakespeare,England,Leicester City,23 February 2017[f],17 October 2017,236,2017,
257,Ole Gunnar Solskjær,Norway,Manchester United,19 December 2018[g],21 November 2021,1068,2018–2021,
288,John Carver,England,Newcastle United,2 January 2015[h],10 June 2015,159,2015,
330,Chris Ramsey,England,Queens Park Rangers,3 February 2015[i],4 November 2015,274,2015,
368,Rubén Sellés,Spain,Southampton,12 February 2023[j],28 May 2023,105,2023,
460,Darren Moore,Jamaica,West Bromwich Albion,2 April 2018[k],9 March 2019,341,2018,

In [10]:
pl_coach['Name'].str.contains('‡')

1      False
2       True
3      False
4       True
5       True
       ...
495    False
496    False
497    False
498     True
499    False
Name: Name, Length: 499, dtype: bool

In [11]:
pl_coach = pl_coach.assign(
    incumbent_manager = np.where(pl_coach['Name'].str.contains('†'), 1, 0),
    caretaker_manager = np.where(pl_coach['Name'].str.contains('‡'), 1, 0),
    incumbent_manager_no_pl = np.where(pl_coach['Name'].str.contains('§'), 1, 0)
)

pl_coach

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl
1,George Graham,Scotland,Arsenal,14 May 1986,21 February 1995,3205,1992–1995,[2],0,0,0
2,Stewart Houston‡,Scotland,Arsenal,22 February 1995,8 June 1995,106,1995,[3],0,1,0
3,Bruce Rioch,Scotland,Arsenal,8 June 1995,12 August 1996,431,1995–1996,[2],0,0,0
4,Stewart Houston‡,Scotland,Arsenal,12 August 1996,13 September 1996,32,1996,[3],0,1,0
5,Pat Rice‡,Northern Ireland,Arsenal,13 September 1996,30 September 1996,17,1996,[4],0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
495,Julen Lopetegui,Spain,Wolverhampton Wanderers,14 November 2022,8 August 2023,267,2022–2023,,0,0,0
496,Gary O'Neil,England,Wolverhampton Wanderers,9 August 2023,15 December 2024,494,2023–2024,,0,0,0
497,Vítor Pereira,Portugal,Wolverhampton Wanderers,19 December 2024,2 November 2025,318,2024–2025,,0,0,0
498,James Collins‡,England,Wolverhampton Wanderers,2 November 2025,12 November 2025,10,2025,,0,1,0
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0

In [12]:
pl_coach['from_check'] = pd.to_datetime(pl_coach['From'], errors='coerce').astype(str)
pl_coach['until_check'] = pd.to_datetime(pl_coach['Until'], errors='coerce').astype(str)

In [13]:
pl_coach[pl_coach['from_check'].str.contains('NaT', case=False) | pl_coach['until_check'].str.contains('NaT', case=False)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check
9,Mikel Arteta†,Spain,Arsenal,22 December 2019,Present*,2196,2019–,[8],1,0,0,2019-12-22,NaT
32,Unai Emery†,Spain,Aston Villa,1 November 2022,Present*,1151,2022–,,1,0,0,2022-11-01,NaT
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,NaT,2023-06-19
58,Andoni Iraola†,Spain,Bournemouth,19 June 2023,Present*,921,2023–,[37],1,0,0,2023-06-19,NaT
64,Keith Andrews†,Republic of Ireland,Brentford,27 June 2025,Present*,182,2025–,,1,0,0,2025-06-27,NaT
67,Roberto De Zerbi,Italy,Brighton & Hove Albion,18 September 2022[b],19 May 2024,1195,2022–2024,,0,0,0,NaT,2024-05-19
68,Fabian Hürzeler†,Germany,Brighton & Hove Albion,2 July 2024,Present*,542,2024–,,1,0,0,2024-07-02,NaT
74,Scott Parker†,England,Burnley,5 July 2024,Present*,539,2025–,,1,0,0,2024-07-05,NaT
111,Enzo Maresca†,Italy,Chelsea,1 July 2024,Present*,543,2024–,,1,0,0,2024-07-01,NaT
138,Oliver Glasner†,Austria,Crystal Palace,19 February 2024,Present*,676,2024–,,1,0,0,2024-02-19,NaT
166,David Moyes†,Scotland,Everton,11 January 2025,Present*,349,2025–,,1,0,0,2025-01-11,NaT
179,Scott Parker,England,Fulham,28 February 2019[c],28 June 2021,851,20192020–2021,,0,0,0,NaT,2021-06-28
180,Marco Silva†,Portugal,Fulham,1 July 2021,Present*,1639,2022–,,1,0,0,2021-07-01,NaT
185,Iain Dowie,Northern Ireland,Hull City,17 March 2010[d],9 May 2010,53,2010,[92],0,0,0,NaT,2010-05-09
187,Mike Phelan,England,Hull City,22 July 2016[e],3 January 2017,165,2016–2017,,0,0,0,NaT,2017-01-03
193,Kieran McKenna§,Northern Ireland,Ipswich Town,16 December 2021,Present*,1471,2024–2025,,0,0,1,2021-12-16,NaT
205,Daniel Farke†,Germany,Leeds United,4 July 2023,Present*,906,2025–,,1,0,0,2023-07-04,NaT
215,Craig Shakespeare,England,Leicester City,23 February 2017[f],17 October 2017,236,2017,,0,0,0,NaT,2017-10-17
237,Arne Slot†,Netherlands,Liverpool,1 June 2024,Present*,573,2024–,,1,0,0,2024-06-01,NaT
251,Pep Guardiola†,Spain,Manchester City,1 July 2016,Present*,3465,2016–,,1,0,0,2016-07-01,NaT
257,Ole Gunnar Solskjær,Norway,Manchester United,19 December 2018[g],21 November 2021,1068,2018–2021,,0,0,0,NaT,2021-11-21
262,Ruben Amorim†,Portugal,Manchester United,11 November 2024,Present*,410,2024–,,1,0,0,2024-11-11,NaT
288,John Carver,England,Newcastle United,2 January 2015[h],10 June 2015,159,2015,,0,0,0,NaT,2015-06-10
293,Eddie Howe†,England,Newcastle United,8 November 2021,Present*,1509,2021–,,1,0,0,2021-11-08,NaT
312,Sean Dyche†,England,Nottingham Forest,21 October 2025,Present*,66,2025–,,1,0,0,2025-10-21,NaT
330,Chris Ramsey,England,Queens Park Rangers,3 February 2015[i],4 November 2015,274,2015,,0,0,0,NaT,2015-11-04
368,Rubén Sellés,Spain,Southampton,12 February 2023[j],28 May 2023,105,2023,,0,0,0,NaT,2023-05-28
391,Régis Le Bris†,France,Sunderland,1 July 2024,Present*,543,2025–,,1,0,0,2024-07-01,NaT
431,Thomas Frank†,Denmark,Tottenham Hotspur,12 June 2025,Present*,197,2025–,,1,0,0,2025-06-12,NaT
460,Darren Moore,Jamaica,West Bromwich Albion,2 April 2018[k],9 March 2019,341,2018,,0,0,0,NaT,2019-03-09
480,Nuno Espírito Santo†,Portugal,West Ham United,27 September 2025,Present*,90,2025–,,1,0,0,2025-09-27,NaT
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0,2025-11-12,NaT

In [14]:
pl_coach[pl_coach['Until'].astype(str).str.contains('present', case=False)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check
9,Mikel Arteta†,Spain,Arsenal,22 December 2019,Present*,2196,2019–,[8],1,0,0,2019-12-22,NaT
32,Unai Emery†,Spain,Aston Villa,1 November 2022,Present*,1151,2022–,,1,0,0,2022-11-01,NaT
58,Andoni Iraola†,Spain,Bournemouth,19 June 2023,Present*,921,2023–,[37],1,0,0,2023-06-19,NaT
64,Keith Andrews†,Republic of Ireland,Brentford,27 June 2025,Present*,182,2025–,,1,0,0,2025-06-27,NaT
68,Fabian Hürzeler†,Germany,Brighton & Hove Albion,2 July 2024,Present*,542,2024–,,1,0,0,2024-07-02,NaT
74,Scott Parker†,England,Burnley,5 July 2024,Present*,539,2025–,,1,0,0,2024-07-05,NaT
111,Enzo Maresca†,Italy,Chelsea,1 July 2024,Present*,543,2024–,,1,0,0,2024-07-01,NaT
138,Oliver Glasner†,Austria,Crystal Palace,19 February 2024,Present*,676,2024–,,1,0,0,2024-02-19,NaT
166,David Moyes†,Scotland,Everton,11 January 2025,Present*,349,2025–,,1,0,0,2025-01-11,NaT
180,Marco Silva†,Portugal,Fulham,1 July 2021,Present*,1639,2022–,,1,0,0,2021-07-01,NaT
193,Kieran McKenna§,Northern Ireland,Ipswich Town,16 December 2021,Present*,1471,2024–2025,,0,0,1,2021-12-16,NaT
205,Daniel Farke†,Germany,Leeds United,4 July 2023,Present*,906,2025–,,1,0,0,2023-07-04,NaT
237,Arne Slot†,Netherlands,Liverpool,1 June 2024,Present*,573,2024–,,1,0,0,2024-06-01,NaT
251,Pep Guardiola†,Spain,Manchester City,1 July 2016,Present*,3465,2016–,,1,0,0,2016-07-01,NaT
262,Ruben Amorim†,Portugal,Manchester United,11 November 2024,Present*,410,2024–,,1,0,0,2024-11-11,NaT
293,Eddie Howe†,England,Newcastle United,8 November 2021,Present*,1509,2021–,,1,0,0,2021-11-08,NaT
312,Sean Dyche†,England,Nottingham Forest,21 October 2025,Present*,66,2025–,,1,0,0,2025-10-21,NaT
391,Régis Le Bris†,France,Sunderland,1 July 2024,Present*,543,2025–,,1,0,0,2024-07-01,NaT
431,Thomas Frank†,Denmark,Tottenham Hotspur,12 June 2025,Present*,197,2025–,,1,0,0,2025-06-12,NaT
480,Nuno Espírito Santo†,Portugal,West Ham United,27 September 2025,Present*,90,2025–,,1,0,0,2025-09-27,NaT
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0,2025-11-12,NaT

In [15]:
pl_coach = pl_coach.assign(
    until_at = np.where(pl_coach['Until'].astype(str).str.contains('present', case=False), datetime.now().date().strftime('%d %B %Y'), pl_coach['Until'])
)

pl_coach['until_at'] = pd.to_datetime(pl_coach['until_at'], format='%d %B %Y')

pl_coach

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at
1,George Graham,Scotland,Arsenal,14 May 1986,21 February 1995,3205,1992–1995,[2],0,0,0,1986-05-14,1995-02-21,1995-02-21
2,Stewart Houston‡,Scotland,Arsenal,22 February 1995,8 June 1995,106,1995,[3],0,1,0,1995-02-22,1995-06-08,1995-06-08
3,Bruce Rioch,Scotland,Arsenal,8 June 1995,12 August 1996,431,1995–1996,[2],0,0,0,1995-06-08,1996-08-12,1996-08-12
4,Stewart Houston‡,Scotland,Arsenal,12 August 1996,13 September 1996,32,1996,[3],0,1,0,1996-08-12,1996-09-13,1996-09-13
5,Pat Rice‡,Northern Ireland,Arsenal,13 September 1996,30 September 1996,17,1996,[4],0,1,0,1996-09-13,1996-09-30,1996-09-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Julen Lopetegui,Spain,Wolverhampton Wanderers,14 November 2022,8 August 2023,267,2022–2023,,0,0,0,2022-11-14,2023-08-08,2023-08-08
496,Gary O'Neil,England,Wolverhampton Wanderers,9 August 2023,15 December 2024,494,2023–2024,,0,0,0,2023-08-09,2024-12-15,2024-12-15
497,Vítor Pereira,Portugal,Wolverhampton Wanderers,19 December 2024,2 November 2025,318,2024–2025,,0,0,0,2024-12-19,2025-11-02,2025-11-02
498,James Collins‡,England,Wolverhampton Wanderers,2 November 2025,12 November 2025,10,2025,,0,1,0,2025-11-02,2025-11-12,2025-11-12
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0,2025-11-12,NaT,2025-12-28

In [16]:
pl_coach[pl_coach['from_check'].str.contains('NaT', case=False)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,NaT,2023-06-19,2023-06-19
67,Roberto De Zerbi,Italy,Brighton & Hove Albion,18 September 2022[b],19 May 2024,1195,2022–2024,,0,0,0,NaT,2024-05-19,2024-05-19
179,Scott Parker,England,Fulham,28 February 2019[c],28 June 2021,851,20192020–2021,,0,0,0,NaT,2021-06-28,2021-06-28
185,Iain Dowie,Northern Ireland,Hull City,17 March 2010[d],9 May 2010,53,2010,[92],0,0,0,NaT,2010-05-09,2010-05-09
187,Mike Phelan,England,Hull City,22 July 2016[e],3 January 2017,165,2016–2017,,0,0,0,NaT,2017-01-03,2017-01-03
215,Craig Shakespeare,England,Leicester City,23 February 2017[f],17 October 2017,236,2017,,0,0,0,NaT,2017-10-17,2017-10-17
257,Ole Gunnar Solskjær,Norway,Manchester United,19 December 2018[g],21 November 2021,1068,2018–2021,,0,0,0,NaT,2021-11-21,2021-11-21
288,John Carver,England,Newcastle United,2 January 2015[h],10 June 2015,159,2015,,0,0,0,NaT,2015-06-10,2015-06-10
330,Chris Ramsey,England,Queens Park Rangers,3 February 2015[i],4 November 2015,274,2015,,0,0,0,NaT,2015-11-04,2015-11-04
368,Rubén Sellés,Spain,Southampton,12 February 2023[j],28 May 2023,105,2023,,0,0,0,NaT,2023-05-28,2023-05-28
460,Darren Moore,Jamaica,West Bromwich Albion,2 April 2018[k],9 March 2019,341,2018,,0,0,0,NaT,2019-03-09,2019-03-09

In [17]:
pl_coach['from_at'] = pl_coach['From'].astype(str).str.replace('\[.*\]', '', regex=True)
pl_coach.loc[[57]]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,NaT,2023-06-19,2023-06-19,30 August 2022

In [18]:
pl_coach.loc[57:59]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,NaT,2023-06-19,2023-06-19,30 August 2022
58,Andoni Iraola†,Spain,Bournemouth,19 June 2023,Present*,921,2023–,[37],1,0,0,2023-06-19,NaT,2025-12-28,19 June 2023
59,Paul Jewell,England,Bradford City,6 January 1998,18 June 2000,894,1999–2000,[38],0,0,0,1998-01-06,2000-06-18,2000-06-18,6 January 1998

In [19]:
pl_coach[pl_coach['From'].astype(str).str.contains('\[.*\]', regex=True)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,NaT,2023-06-19,2023-06-19,30 August 2022
67,Roberto De Zerbi,Italy,Brighton & Hove Albion,18 September 2022[b],19 May 2024,1195,2022–2024,,0,0,0,NaT,2024-05-19,2024-05-19,18 September 2022
179,Scott Parker,England,Fulham,28 February 2019[c],28 June 2021,851,20192020–2021,,0,0,0,NaT,2021-06-28,2021-06-28,28 February 2019
185,Iain Dowie,Northern Ireland,Hull City,17 March 2010[d],9 May 2010,53,2010,[92],0,0,0,NaT,2010-05-09,2010-05-09,17 March 2010
187,Mike Phelan,England,Hull City,22 July 2016[e],3 January 2017,165,2016–2017,,0,0,0,NaT,2017-01-03,2017-01-03,22 July 2016
215,Craig Shakespeare,England,Leicester City,23 February 2017[f],17 October 2017,236,2017,,0,0,0,NaT,2017-10-17,2017-10-17,23 February 2017
257,Ole Gunnar Solskjær,Norway,Manchester United,19 December 2018[g],21 November 2021,1068,2018–2021,,0,0,0,NaT,2021-11-21,2021-11-21,19 December 2018
288,John Carver,England,Newcastle United,2 January 2015[h],10 June 2015,159,2015,,0,0,0,NaT,2015-06-10,2015-06-10,2 January 2015
330,Chris Ramsey,England,Queens Park Rangers,3 February 2015[i],4 November 2015,274,2015,,0,0,0,NaT,2015-11-04,2015-11-04,3 February 2015
368,Rubén Sellés,Spain,Southampton,12 February 2023[j],28 May 2023,105,2023,,0,0,0,NaT,2023-05-28,2023-05-28,12 February 2023
460,Darren Moore,Jamaica,West Bromwich Albion,2 April 2018[k],9 March 2019,341,2018,,0,0,0,NaT,2019-03-09,2019-03-09,2 April 2018

In [20]:
pd.to_datetime(pl_coach.loc[[57]]['from_at'], format='%d %B %Y', errors='coerce').astype(str)

57    2022-08-30
Name: from_at, dtype: object

In [21]:
pl_coach = pl_coach.assign(
from_at = np.where(pl_coach['From'].astype(str).str.contains('\[.*\]', regex=True)
         , pd.to_datetime(pl_coach['from_at'], format='%d %B %Y', errors='coerce')
         , pd.to_datetime(pl_coach['from_at'], errors='coerce'))
)

pl_coach

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
1,George Graham,Scotland,Arsenal,14 May 1986,21 February 1995,3205,1992–1995,[2],0,0,0,1986-05-14,1995-02-21,1995-02-21,1986-05-14
2,Stewart Houston‡,Scotland,Arsenal,22 February 1995,8 June 1995,106,1995,[3],0,1,0,1995-02-22,1995-06-08,1995-06-08,1995-02-22
3,Bruce Rioch,Scotland,Arsenal,8 June 1995,12 August 1996,431,1995–1996,[2],0,0,0,1995-06-08,1996-08-12,1996-08-12,1995-06-08
4,Stewart Houston‡,Scotland,Arsenal,12 August 1996,13 September 1996,32,1996,[3],0,1,0,1996-08-12,1996-09-13,1996-09-13,1996-08-12
5,Pat Rice‡,Northern Ireland,Arsenal,13 September 1996,30 September 1996,17,1996,[4],0,1,0,1996-09-13,1996-09-30,1996-09-30,1996-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Julen Lopetegui,Spain,Wolverhampton Wanderers,14 November 2022,8 August 2023,267,2022–2023,,0,0,0,2022-11-14,2023-08-08,2023-08-08,2022-11-14
496,Gary O'Neil,England,Wolverhampton Wanderers,9 August 2023,15 December 2024,494,2023–2024,,0,0,0,2023-08-09,2024-12-15,2024-12-15,2023-08-09
497,Vítor Pereira,Portugal,Wolverhampton Wanderers,19 December 2024,2 November 2025,318,2024–2025,,0,0,0,2024-12-19,2025-11-02,2025-11-02,2024-12-19
498,James Collins‡,England,Wolverhampton Wanderers,2 November 2025,12 November 2025,10,2025,,0,1,0,2025-11-02,2025-11-12,2025-11-12,2025-11-02
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0,2025-11-12,NaT,2025-12-28,2025-11-12

In [22]:
pl_coach['from_check'] = pd.to_datetime(pl_coach['from_at'], errors='coerce').astype(str)
pl_coach['until_check'] = pd.to_datetime(pl_coach['until_at'], errors='coerce').astype(str)

In [23]:
pl_coach[pl_coach['from_check'].str.contains('NaT', case=False) | pl_coach['until_check'].str.contains('NaT', case=False)]

Empty DataFrame
Columns: [Name, Nat., Club, From, Until, Duration(days), Years inLeague, Ref., incumbent_manager, caretaker_manager, incumbent_manager_no_pl, from_check, until_check, until_at, from_at]
Index: []

In [24]:
pl_coach

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
1,George Graham,Scotland,Arsenal,14 May 1986,21 February 1995,3205,1992–1995,[2],0,0,0,1986-05-14,1995-02-21,1995-02-21,1986-05-14
2,Stewart Houston‡,Scotland,Arsenal,22 February 1995,8 June 1995,106,1995,[3],0,1,0,1995-02-22,1995-06-08,1995-06-08,1995-02-22
3,Bruce Rioch,Scotland,Arsenal,8 June 1995,12 August 1996,431,1995–1996,[2],0,0,0,1995-06-08,1996-08-12,1996-08-12,1995-06-08
4,Stewart Houston‡,Scotland,Arsenal,12 August 1996,13 September 1996,32,1996,[3],0,1,0,1996-08-12,1996-09-13,1996-09-13,1996-08-12
5,Pat Rice‡,Northern Ireland,Arsenal,13 September 1996,30 September 1996,17,1996,[4],0,1,0,1996-09-13,1996-09-30,1996-09-30,1996-09-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Julen Lopetegui,Spain,Wolverhampton Wanderers,14 November 2022,8 August 2023,267,2022–2023,,0,0,0,2022-11-14,2023-08-08,2023-08-08,2022-11-14
496,Gary O'Neil,England,Wolverhampton Wanderers,9 August 2023,15 December 2024,494,2023–2024,,0,0,0,2023-08-09,2024-12-15,2024-12-15,2023-08-09
497,Vítor Pereira,Portugal,Wolverhampton Wanderers,19 December 2024,2 November 2025,318,2024–2025,,0,0,0,2024-12-19,2025-11-02,2025-11-02,2024-12-19
498,James Collins‡,England,Wolverhampton Wanderers,2 November 2025,12 November 2025,10,2025,,0,1,0,2025-11-02,2025-11-12,2025-11-12,2025-11-02
499,Rob Edwards†,Wales,Wolverhampton Wanderers,12 November 2025,Present*,44,2025–,,1,0,0,2025-11-12,2025-12-28,2025-12-28,2025-11-12

In [25]:
coach_team = coach_df.merge(team_df[['team_id', 'name', 'league_id']].rename({'name':'club_name'}, axis=1), how='left', on='team_id')
coach_team = coach_team[coach_team['league_id']==1]
coach_team

,coach_id,name,team_id,nationality,club_name,league_id
0,34,NaN,354,NaN,Crystal Palace,1
1,35,NaN,356,NaN,Sheffield United,1
2,36,NaN,389,NaN,Luton Town,1
3,37,NaN,397,NaN,Brighton & Hove Albion,1
4,38,NaN,402,NaN,Brentford,1
5,39,NaN,563,NaN,West Ham United,1
6,40,NaN,1044,NaN,AFC Bournemouth,1
83,31,Gary O'Neil,76,NaN,Wolverhampton Wanderers,1
84,21,Mikel Arteta,57,Spain,Arsenal,1
85,22,Unai Emery,58,Spain,Aston Villa,1
86,26,Jürgen Klopp,64,Germany,Liverpool,1
87,23,Enzo Maresca,61,Italy,Chelsea,1
88,24,Sean Dyche,62,England,Everton,1
89,25,Marco Silva,63,Portugal,Fulham,1
90,27,Pep Guardiola,65,Spain,Manchester City,1
91,28,Erik ten Hag,66,Netherlands,Manchester United,1
92,29,Eddie Howe,67,England,Newcastle United,1
93,30,Ange Postecoglou,73,Greece,Tottenham Hotspur,1
94,32,Vincent Kompany,328,Belgium,Burnley,1
95,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1

In [26]:
coach_pl = coach_team.merge(pl_coach, how='left', left_on='club_name', right_on='Club')
coach_pl

,coach_id,name,team_id,nationality,club_name,league_id,Name,Nat.,Club,From,...,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
0,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,3 June 1984,...,3270,1992–1993,[67],0.0,0.0,0.0,1984-06-03,1993-05-17,1993-05-17,1984-06-03
1,34,NaN,354,NaN,Crystal Palace,1,Alan Smith,England,Crystal Palace,3 June 1993,...,711,1994–1995,[67],0.0,0.0,0.0,1993-06-03,1995-05-15,1995-05-15,1993-06-03
2,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,27 February 1997,...,379,1997–1998,[67],0.0,0.0,0.0,1997-02-27,1998-03-13,1998-03-13,1997-02-27
3,34,NaN,354,NaN,Crystal Palace,1,Attilio Lombardo‡,Italy,Crystal Palace,13 March 1998,...,47,1998,[67],0.0,1.0,0.0,1998-03-13,1998-04-29,1998-04-29,1998-03-13
4,34,NaN,354,NaN,Crystal Palace,1,Tomas Brolin‡,Sweden,Crystal Palace,13 March 1998,...,47,1998,[67],0.0,1.0,0.0,1998-03-13,1998-04-29,1998-04-29,1998-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
262,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Ron Atkinson,England,Nottingham Forest,11 January 1999,...,125,1999,[112][113],0.0,0.0,0.0,1999-01-11,1999-05-16,1999-05-16,1999-01-11
263,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Steve Cooper,Wales,Nottingham Forest,21 September 2021,...,819,2022–2023,,0.0,0.0,0.0,2021-09-21,2023-12-19,2023-12-19,2021-09-21
264,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Nuno Espírito Santo,Portugal,Nottingham Forest,20 December 2023,...,629,2023–2025,,0.0,0.0,0.0,2023-12-20,2025-09-09,2025-09-09,2023-12-20
265,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Ange Postecoglou,Australia,Nottingham Forest,9 September 2025,...,39,2025,,0.0,0.0,0.0,2025-09-09,2025-10-18,2025-10-18,2025-09-09
266,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Sean Dyche†,England,Nottingham Forest,21 October 2025,...,66,2025–,,1.0,0.0,0.0,2025-10-21,2025-12-28,2025-12-28,2025-10-21

In [27]:
coach_pl.isnull().any()

coach_id                   False
name                        True
team_id                    False
nationality                 True
club_name                  False
league_id                  False
Name                        True
Nat.                        True
Club                        True
From                        True
Until                       True
Duration(days)              True
Years inLeague              True
Ref.                        True
incumbent_manager           True
caretaker_manager           True
incumbent_manager_no_pl     True
from_check                  True
until_check                 True
until_at                    True
from_at                     True
dtype: bool

In [28]:
coach_pl[coach_pl['Name'].isnull()]

,coach_id,name,team_id,nationality,club_name,league_id,Name,Nat.,Club,From,...,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
54,40,NaN,1044,NaN,AFC Bournemouth,1,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaT

In [29]:
pl_coach[pl_coach['Club'].str.contains('bournemouth', case=False)]

,Name,Nat.,Club,From,Until,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
55,Eddie Howe,England,Bournemouth,12 October 2012,1 August 2020,2850,2015–2020,[35],0,0,0,2012-10-12,2020-08-01,2020-08-01,2012-10-12
56,Scott Parker,England,Bournemouth,28 June 2021,30 August 2022,428,2022,,0,0,0,2021-06-28,2022-08-30,2022-08-30,2021-06-28
57,Gary O'Neil,England,Bournemouth,30 August 2022[a],19 June 2023,293,2022–2023,[36],0,0,0,2022-08-30,2023-06-19,2023-06-19,2022-08-30
58,Andoni Iraola†,Spain,Bournemouth,19 June 2023,Present*,921,2023–,[37],1,0,0,2023-06-19,2025-12-28,2025-12-28,2023-06-19

In [30]:
pl_coach['Club'] = pl_coach['Club'].str.replace('Bournemouth', 'AFC Bournemouth')

In [31]:
coach_pl = coach_team.merge(pl_coach, how='left', left_on='club_name', right_on='Club')
coach_pl

,coach_id,name,team_id,nationality,club_name,league_id,Name,Nat.,Club,From,...,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
0,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,3 June 1984,...,3270,1992–1993,[67],0,0,0,1984-06-03,1993-05-17,1993-05-17,1984-06-03
1,34,NaN,354,NaN,Crystal Palace,1,Alan Smith,England,Crystal Palace,3 June 1993,...,711,1994–1995,[67],0,0,0,1993-06-03,1995-05-15,1995-05-15,1993-06-03
2,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,27 February 1997,...,379,1997–1998,[67],0,0,0,1997-02-27,1998-03-13,1998-03-13,1997-02-27
3,34,NaN,354,NaN,Crystal Palace,1,Attilio Lombardo‡,Italy,Crystal Palace,13 March 1998,...,47,1998,[67],0,1,0,1998-03-13,1998-04-29,1998-04-29,1998-03-13
4,34,NaN,354,NaN,Crystal Palace,1,Tomas Brolin‡,Sweden,Crystal Palace,13 March 1998,...,47,1998,[67],0,1,0,1998-03-13,1998-04-29,1998-04-29,1998-03-13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Ron Atkinson,England,Nottingham Forest,11 January 1999,...,125,1999,[112][113],0,0,0,1999-01-11,1999-05-16,1999-05-16,1999-01-11
266,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Steve Cooper,Wales,Nottingham Forest,21 September 2021,...,819,2022–2023,,0,0,0,2021-09-21,2023-12-19,2023-12-19,2021-09-21
267,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Nuno Espírito Santo,Portugal,Nottingham Forest,20 December 2023,...,629,2023–2025,,0,0,0,2023-12-20,2025-09-09,2025-09-09,2023-12-20
268,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Ange Postecoglou,Australia,Nottingham Forest,9 September 2025,...,39,2025,,0,0,0,2025-09-09,2025-10-18,2025-10-18,2025-09-09
269,33,Nuno Espirito Santo,351,Portugal,Nottingham Forest,1,Sean Dyche†,England,Nottingham Forest,21 October 2025,...,66,2025–,,1,0,0,2025-10-21,2025-12-28,2025-12-28,2025-10-21

In [32]:
coach_pl.isnull().any()

coach_id                   False
name                        True
team_id                    False
nationality                 True
club_name                  False
league_id                  False
Name                       False
Nat.                       False
Club                       False
From                       False
Until                      False
Duration(days)             False
Years inLeague             False
Ref.                       False
incumbent_manager          False
caretaker_manager          False
incumbent_manager_no_pl    False
from_check                 False
until_check                False
until_at                   False
from_at                    False
dtype: bool

In [33]:
coach_pl[coach_pl['name'].isnull()].head(5)

,coach_id,name,team_id,nationality,club_name,league_id,Name,Nat.,Club,From,...,Duration(days),Years inLeague,Ref.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,from_check,until_check,until_at,from_at
0,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,3 June 1984,...,3270,1992–1993,[67],0,0,0,1984-06-03,1993-05-17,1993-05-17,1984-06-03
1,34,NaN,354,NaN,Crystal Palace,1,Alan Smith,England,Crystal Palace,3 June 1993,...,711,1994–1995,[67],0,0,0,1993-06-03,1995-05-15,1995-05-15,1993-06-03
2,34,NaN,354,NaN,Crystal Palace,1,Steve Coppell,England,Crystal Palace,27 February 1997,...,379,1997–1998,[67],0,0,0,1997-02-27,1998-03-13,1998-03-13,1997-02-27
3,34,NaN,354,NaN,Crystal Palace,1,Attilio Lombardo‡,Italy,Crystal Palace,13 March 1998,...,47,1998,[67],0,1,0,1998-03-13,1998-04-29,1998-04-29,1998-03-13
4,34,NaN,354,NaN,Crystal Palace,1,Tomas Brolin‡,Sweden,Crystal Palace,13 March 1998,...,47,1998,[67],0,1,0,1998-03-13,1998-04-29,1998-04-29,1998-03-13

In [34]:
coach_pl.columns

Index(['coach_id', 'name', 'team_id', 'nationality', 'club_name', 'league_id',
       'Name', 'Nat.', 'Club', 'From', 'Until', 'Duration(days)',
       'Years inLeague', 'Ref.', 'incumbent_manager', 'caretaker_manager',
       'incumbent_manager_no_pl', 'from_check', 'until_check', 'until_at',
       'from_at'],
      dtype='object')

In [35]:
coach_pl_scd = coach_pl[['coach_id', 'team_id', 'club_name', 'league_id','Name', 'Nat.','incumbent_manager', 'caretaker_manager', 'incumbent_manager_no_pl','until_at', 'from_at']]
coach_pl_scd

,coach_id,team_id,club_name,league_id,Name,Nat.,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,until_at,from_at
0,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1993-05-17,1984-06-03
1,34,354,Crystal Palace,1,Alan Smith,England,0,0,0,1995-05-15,1993-06-03
2,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1998-03-13,1997-02-27
3,34,354,Crystal Palace,1,Attilio Lombardo‡,Italy,0,1,0,1998-04-29,1998-03-13
4,34,354,Crystal Palace,1,Tomas Brolin‡,Sweden,0,1,0,1998-04-29,1998-03-13
...,...,...,...,...,...,...,...,...,...,...,...
265,33,351,Nottingham Forest,1,Ron Atkinson,England,0,0,0,1999-05-16,1999-01-11
266,33,351,Nottingham Forest,1,Steve Cooper,Wales,0,0,0,2023-12-19,2021-09-21
267,33,351,Nottingham Forest,1,Nuno Espírito Santo,Portugal,0,0,0,2025-09-09,2023-12-20
268,33,351,Nottingham Forest,1,Ange Postecoglou,Australia,0,0,0,2025-10-18,2025-09-09
269,33,351,Nottingham Forest,1,Sean Dyche†,England,1,0,0,2025-12-28,2025-10-21

In [36]:
coach_pl_scd = coach_pl_scd.rename({
    'Name':'coach_name'
    , 'Nat.':'nationality'
}, axis=1)

coach_pl_scd

,coach_id,team_id,club_name,league_id,coach_name,nationality,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,until_at,from_at
0,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1993-05-17,1984-06-03
1,34,354,Crystal Palace,1,Alan Smith,England,0,0,0,1995-05-15,1993-06-03
2,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1998-03-13,1997-02-27
3,34,354,Crystal Palace,1,Attilio Lombardo‡,Italy,0,1,0,1998-04-29,1998-03-13
4,34,354,Crystal Palace,1,Tomas Brolin‡,Sweden,0,1,0,1998-04-29,1998-03-13
...,...,...,...,...,...,...,...,...,...,...,...
265,33,351,Nottingham Forest,1,Ron Atkinson,England,0,0,0,1999-05-16,1999-01-11
266,33,351,Nottingham Forest,1,Steve Cooper,Wales,0,0,0,2023-12-19,2021-09-21
267,33,351,Nottingham Forest,1,Nuno Espírito Santo,Portugal,0,0,0,2025-09-09,2023-12-20
268,33,351,Nottingham Forest,1,Ange Postecoglou,Australia,0,0,0,2025-10-18,2025-09-09
269,33,351,Nottingham Forest,1,Sean Dyche†,England,1,0,0,2025-12-28,2025-10-21

In [37]:
coach_pl_scd['coach_name'] = coach_pl_scd['coach_name'].str.replace('†|‡|§', '', regex=True)
coach_pl_scd

,coach_id,team_id,club_name,league_id,coach_name,nationality,incumbent_manager,caretaker_manager,incumbent_manager_no_pl,until_at,from_at
0,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1993-05-17,1984-06-03
1,34,354,Crystal Palace,1,Alan Smith,England,0,0,0,1995-05-15,1993-06-03
2,34,354,Crystal Palace,1,Steve Coppell,England,0,0,0,1998-03-13,1997-02-27
3,34,354,Crystal Palace,1,Attilio Lombardo,Italy,0,1,0,1998-04-29,1998-03-13
4,34,354,Crystal Palace,1,Tomas Brolin,Sweden,0,1,0,1998-04-29,1998-03-13
...,...,...,...,...,...,...,...,...,...,...,...
265,33,351,Nottingham Forest,1,Ron Atkinson,England,0,0,0,1999-05-16,1999-01-11
266,33,351,Nottingham Forest,1,Steve Cooper,Wales,0,0,0,2023-12-19,2021-09-21
267,33,351,Nottingham Forest,1,Nuno Espírito Santo,Portugal,0,0,0,2025-09-09,2023-12-20
268,33,351,Nottingham Forest,1,Ange Postecoglou,Australia,0,0,0,2025-10-18,2025-09-09
269,33,351,Nottingham Forest,1,Sean Dyche,England,1,0,0,2025-12-28,2025-10-21

In [38]:
coach_pl_scd.isnull().any()

coach_id                   False
team_id                    False
club_name                  False
league_id                  False
coach_name                 False
nationality                False
incumbent_manager          False
caretaker_manager          False
incumbent_manager_no_pl    False
until_at                   False
from_at                    False
dtype: bool

In [39]:
coach_pl_scd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   coach_id                 270 non-null    int64
 1   team_id                  270 non-null    int64
 2   club_name                270 non-null    object
 3   league_id                270 non-null    int64
 4   coach_name               270 non-null    object
 5   nationality              270 non-null    object
 6   incumbent_manager        270 non-null    int64
 7   caretaker_manager        270 non-null    int64
 8   incumbent_manager_no_pl  270 non-null    int64
 9   until_at                 270 non-null    datetime64[ns]
 10  from_at                  270 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(6), object(3)
memory usage: 23.3+ KB

In [40]:
# Load the csv file to database

pipe.export_df_to_sql(coach_pl_scd, "coaches_scd_test")

--- Checking/Creating Database: 'football' ---
Database 'football' is ready.
--- Exporting DataFrame to table 'coaches_scd_test' ---
Successfully exported 270 rows to 'coaches_scd_test'.